### ISSUE TITLE
Software class redundant with IAO?

### ISSUE THREAD

**Issue by jb1138** [allysonlister/swo#1]
note, this issue is also been posted to IAO Discussion Group at:
https://groups.google.com/forum/#!topic/information-ontology/S07ghF9lGY0

We've been using SWO with great success now for a month.  I have one major issue / question:

SWO defines the class "software" (http://www.ebi.ac.uk/swo/SWO_0000001) as a subclass of IAO:information content entity (http://purl.obolibrary.org/obo/IAO_0000030)
URI = http://www.ebi.ac.uk/swo/SWO_0000001
def = Computer software, or generally just software, is any set of machine-readable instructions (most often in the form of a computer program) that conform to a given syntax (sometimes referred to as a language) that is interpretable by a given processor and that directs a computer's processor to perform specific operations.

This class seems redundant with IAO:Software (http://purl.obolibrary.org/obo/IAO_0000010)
class hierarchy = information content entity / directive information entity / plan specification / Software
URI = http://purl.obolibrary.org/obo/IAO_0000010
def = Software is a plan specification composed of a series of instructions that can be interpreted by or directly executed by a processing unit.

Should SWO:Software be deleted and it's subclasses  moved under IAO:Software to maximize ontology reuse, maintain clean separation between upper / middle / domain ontologies, and to minimize confusion and redundancy?

**Comment by allysonlister** [comment]
Thanks for the thought. I've had a word with @jamesmalone and @TheOntologist and our plan is to put in an equivalence axiom between the two classes, roughly:
 
> IAO:software EquivalentTo: SWO:software
 
 This would preserve any previous annotations, and be a simple fix to implement. I work part time, and so I plan to add this on Tuesday afternoon...

Thanks very much!

**Comment by jb1138** [comment]
Declaring class equivalence may introduce confusion, as these classes are at different levels in the hierarchy.  I haven't fully thought through the reasoning implications of this change.

I'm wondering if you would consider any of the following options:

a) moving the software class to a "deprecated" or "obsolete class" branch of the SWO ontology.  Some ontologies place such a class directly under owl:Thing.  This eliminates it from the upper ontology, i.e., BFO, for those systems that only consider classes under the upper ontology but leaves it available for those systems that already have a reference (until they can be updated).  Additionally a note would be added pointing to the recommended class to be used (IAO:software in this case)

b) moving the SWO:software as a subclass of IAO:software so at least they are at a similar depth in the class hierarchy.  A comment could be added to "deprecate" the class, it's label changed to "deprecated_software" and all of its subclasses could be moved under IAO:software.  Again the URI is preserved for those annotations that already exist.

There may be another best practice for what to do recommended by OBO Foundry

**Comment by allysonlister** [comment]
Yes, Robert has just sent me an email stating that we would need to look into this in more detail. We will look into it further, and post here as we think about it. Thanks!

**Comment by jb1138** [comment]
Hi Allyson.  Just checking in to see if there had been any further discussion on this issue.  

Thanks!
-joe

**Comment by allysonlister** [comment]
Thanks so much for the gentle reminder. I am on my summer hols right now (I only work part time during term time) but I'll keep this in my inbox to look at in September. I do admit I slightly lost it in my inbox the first time, so I'll add a proper reminder in this time. Thanks very much! :)

**Comment by allysonlister** [comment]
Very sorry that this was left unresolved for so long. My initial feeling is to make our software class redundant, but I will once again confer with @TheOntologist and @jamesmalone as well as Helen P. This has been added to the milestone for our next release, hopefully out by early October.

Thanks!

**Comment by jamesmalone** [comment]
I think this is probably fine. My one caveat is after (many) conversations with IAO in the past they were clear software should be largely expressed as individuals rather than classes which is not how we have modelled them. Based on that understanding - that out software and components are classes - I'd be fine with moving to the IAO software class. I suspect the implications of this are pretty small tbh.

**Comment by allysonlister** [comment]
That is interesting, thanks for the insight @jamesmalone - I appreciate your thoughts. I can put an editor note / comment in if we make the change. Will just wait and see a day or so and see if anyone else wants to weigh in before I make the change.

Thanks! :)

**Comment by TheOntologist** [comment]
I’m disinclined to do this one. The implication of doing so is that we would have to re-model every software as an individual. I could go as far as putting in an annotation saying “this is sort of the same as IAO:Software”


It all comes down to ontological Commitment.

**Comment by allysonlister** [comment]
Thanks @TheOntologist - I am now torn as to which way to go :-) 

On the one hand, there is a significant-enough difference between the two classes and how they treat software 'things', and on the other hand there is the idea that we could align with IAO more closely.

After Robert's thoughts, I'm now leaning towards keeping the SWO term and just putting a comment in, as he has suggested.

@jamesmalone what are your thoughts now? Though it may look as though I'm easily swayed, I also do see both sides of things ;-)

Thanks guys!

**Comment by jamesmalone** [comment]
Our get out I suppose is that they can pun on our classes if they want to
treat them as individuals. We shouldn't change our modelling process
though. There's nothing in the IAO class of software that states software
should be all instance level so I don't think we're misusing it, more that
I know the opinion of a few IAO developers was that they are individuals.
But I don't have strong opinions either way tbh. I'm always happy to reuse
if appropriate.

**Comment by TheOntologist** [comment]
Properly, which is a thing upon which I’m inconsistent, if we’re aligning to BFO compliant ontologies, then we should be BFO compliant and do it the bFO way.

The other hand is that we just do it, it’s improper, but it keeps someone happy and the issue  goes away. It may upset some OntoNazis, but then we can just take the equivalence axiom away again.

I wold, however, be still disinclined.

**Comment by allysonlister** [comment]
Robert - by "I would still be disinclined" do you mean that you would be disinclined to place any kind of ontological equivalence between SWO software and IAO software? 

:) Ally

**Comment by TheOntologist** [comment]
Yes, not do it.

**Comment by allysonlister** [comment]
To confirm our decision: We will not be making IAO software and SWO software equivalent, due to the differences in how software is modelled in the two ontologies. We appreciate that there are similarities, but feel the differences outweigh them at this stage.  The primary difference is that IAO software is intended to be modelled with software as instances, while in SWO we use classes.

No need to add anything to the ontology, as the discussion has been had here.
