### ISSUE TITLE
New term: BCBio

### ISSUE THREAD

**Issue by allysonlister** [allysonlister/swo#11]
Please could @drmarkreuter provide:
1. homepage
2. definition (i.e. purpose)
3. licence info

Apologies for a lack of official term suggestion guidelines - we're volunteer run, and have to budget our time!

Split from #10.

**Comment by drmarkreuter** [comment]
bcbio

https://github.com/bcbio/bcbio-nextgen

bcbio provides a shared community resource that handles the data processing component of sequencing analysis, providing researchers with more time to focus on the downstream biology.

The code is freely available under the MIT license.

**Comment by allysonlister** [comment]
Assigned http://www.ebi.ac.uk/swo/SWO_1100128
