### ISSUE TITLE
New term: ShinyNGS

### ISSUE THREAD

**Issue by allysonlister** [allysonlister/swo#12]
Please could @drmarkreuter provide:
1. homepage
2. definition (i.e. purpose)
3. licence info

Apologies for a lack of official term suggestion guidelines - we're volunteer run, and have to budget our time!

Split from #10.

Feel free to add any others to the issue tracker. Thanks!

**Comment by drmarkreuter** [comment]
shinyNGS

https://github.com/pinin4fjords/shinyngs

Shinyngs is an R package designed to facilitate downstream analysis of RNA-seq and similar expression data with various exploratory plots and data mining tools.

GNU Affero General Public License v3.0

**Comment by allysonlister** [comment]
Assigned to http://www.ebi.ac.uk/swo/SWO_1100129
