### ISSUE TITLE
Please add new term to SWO: Seurat

### ISSUE THREAD

**Issue by drmarkreuter** [allysonlister/swo#13]
Seurat

https://satijalab.org/seurat/

Seurat is an R package designed for QC, analysis, and exploration of single-cell RNA-seq data. Seurat aims to enable users to identify and interpret sources of heterogeneity from single-cell transcriptomic measurements, and to integrate diverse types of single-cell data.

GNU Public License (GPL 3.0)

**Comment by allysonlister** [comment]
Assigned to http://www.ebi.ac.uk/swo/SWO_1100130
