### ISSUE TITLE
Please add new term to SWO: Graphpad Prism

### ISSUE THREAD

**Issue by drmarkreuter** [allysonlister/swo#14]
Graphpad Prism

https://www.graphpad.com/scientific-software/prism/

GraphPad Prism is a commercial scientific 2D graphing and statistics software available for both Windows and Macintosh computers.

Commercial software with 30 day trial period

**Comment by allysonlister** [comment]
Assigned to http://www.ebi.ac.uk/swo/SWO_1100131

**Comment by allysonlister** [comment]
Used 'Proprietary commercial software licence'.
