### ISSUE TITLE
Please add new term: Salmon

### ISSUE THREAD

**Issue by drmarkreuter** [allysonlister/swo#15]
Salmon

https://combine-lab.github.io/salmon/

Salmon is a tool for quantifying the expression of transcripts using RNA-seq data. Salmon uses new algorithms (specifically, coupling the concept of quasi-mapping with a two-phase inference procedure) to provide accurate expression estimates very quickly (i.e. wicked-fast) and while using little memory. Salmon performs its inference using an expressive and realistic model of RNA-seq data that takes into account experimental attributes and biases commonly observed in real RNA-seq data.

GNU GENERAL PUBLIC LICENSE Version 3

**Comment by allysonlister** [comment]
Assigned to http://www.ebi.ac.uk/swo/SWO_1100132
