### ISSUE TITLE
duplicate classes for software development

### ISSUE THREAD

**Issue by hoganwr** [allysonlister/swo#2]
Class 1:
    IRI: http://www.ebi.ac.uk/swo/objective/SWO_4000007
    label: "software development"
    parent class label: "information processing"

Class 2:
    IRI: http://www.ebi.ac.uk/swo/organization/SWO_9000056
    label: "software development process"
    parent class label: "process"

Class 2 has a definition, so I'm assuming it's the one you intend folks to use, but I'm holding off until one of them is deprecated.

**Comment by allysonlister** [comment]
Apologies for the late reply - we are volunteer led, and are now building a release, so I'm looking at this.

Agreed, both of these classes are in the process hierarchy, and we certainly don't need them both. Class 2 has more annotation and also more usage, though the placement in the hierarchy for Class 1 is better.

Unless anyone has any reason to the contrary, in the next day or two I will:

1. Move http://www.ebi.ac.uk/swo/organization/SWO_9000056 as a child of 'data transformation' (sibling of http://www.ebi.ac.uk/swo/objective/SWO_4000007).
2. Refactor http://www.ebi.ac.uk/swo/objective/SWO_4000007 by moving all its axioms to http://www.ebi.ac.uk/swo/organization/SWO_9000056
3. Obsolete http://www.ebi.ac.uk/swo/objective/SWO_4000007
4. I think removing the "process" from the label of http://www.ebi.ac.uk/swo/organization/SWO_9000056 would make sense too.

Thanks!

**Comment by jamesmalone** [comment]
Agreed Ally, would be useful in class be made obsolete to add a replaced by annotation pointing to the one that should be used to.
