### ISSUE TITLE
Please add new term: FastQC

### ISSUE THREAD

**Issue by drmarkreuter** [allysonlister/swo#23]
FastQC

https://github.com/s-andrews/FastQC

FastQC aims to provide a simple way to do some quality control checks on raw sequence data coming from high throughput sequencing pipelines. It provides a modular set of analyses which you can use to give a quick impression of whether your data has any problems of which you should be aware before doing any further analysis.

GNU GENERAL PUBLIC LICENSE Version 2

**Comment by allysonlister** [comment]
Assigned SWO:1100144
