### ISSUE TITLE
Please add new term: RSeQC

### ISSUE THREAD

**Issue by drmarkreuter** [allysonlister/swo#25]
RSeQC

http://rseqc.sourceforge.net/

RSeQC package provides a number of useful modules that can comprehensively evaluate high throughput sequence data especially RNA-seq data. Some basic modules quickly inspect sequence quality, nucleotide composition bias, PCR bias and GC bias, while RNA-seq specific modules evaluate sequencing saturation, mapped reads distribution, coverage uniformity, strand specificity, transcript level RNA integrity etc.

 GNU General Public License (GPLv3)

**Comment by allysonlister** [comment]
Assigned SWO:1100142
