### ISSUE TITLE
Please add new term: RNA-SeQC

### ISSUE THREAD

**Issue by drmarkreuter** [allysonlister/swo#26]
RNA-SeQC

https://github.com/broadinstitute/rnaseqc

RNA-SeQC is a java program which computes a series of quality control metrics for RNA-seq data. The input can be one or more BAM files. The output consists of HTML reports and tab delimited files of metrics data. This program can be valuable for comparing sequencing quality across different samples or experiments to evaluate different experimental parameters. It can also be run on individual samples as a means of quality control before continuing with downstream analysis.

BSD 3-clause license

**Comment by allysonlister** [comment]
Assigned SWO:1100141
