### ISSUE TITLE
Please add new term: PEAKS DB

### ISSUE THREAD

**Issue by drmarkreuter** [allysonlister/swo#28]
PEAKS DB

http://www.bioinfor.com/peaksdb/

Protein Identification Software including an LC-MS/MS search engine, modification search and PTM profiling, sequence variant search, integration with de novo sequencing, and support for all types of fragment ions.

Proprietary commercial software licence

**Comment by allysonlister** [comment]
Although this has "DB" in its name, it is database software that can be downloaded and implemented locally, rather than a database instance you visit / search / upload data to. Therefore applicable for SWO. Assigned SWO:1100139
