### ISSUE TITLE
Typo in definition for "Development status" (SWO_9000061)

### ISSUE THREAD

**Issue by jb1138** [allysonlister/swo#3]
The human readable definition (obo:IAO_0000115) for SWO_9000061 currently reads:
Development status is an information content entity which indicates the maturity of a sofrware entity within the context of the software life cycle.

The word "sofrware" is a typo and should be corrected to "software"

**Comment by allysonlister** [comment]
Thanks very much for letting us know! I'll modify the OWL this week and get back to you.

**Comment by allysonlister** [comment]
Fixed.
