### ISSUE TITLE
Please add new term: SWATH Software

### ISSUE THREAD

**Issue by drmarkreuter** [allysonlister/swo#30]
SWATH Software

https://sciex.com/technology/swath-acquisition

SWATH is the only data independent acquisition (DIA) technique that allows comprehensive detection and quantitation of virtually every detectable compound in a sample (MS/MSALL). This provides confidence in your quantitative results and virtually eliminates the risk of missing a critical component. SWATH Acquisition strategy can only be achieved through the power and speed of SCIEX TripleTOF® and QTOF technology.

Proprietary commercial software licence

**Comment by allysonlister** [comment]
Assigned SWO:1100137
