### ISSUE TITLE
Please add new term: AnalyzerPro

### ISSUE THREAD

**Issue by drmarkreuter** [allysonlister/swo#31]
AnalyzerPro

https://www.spectralworks.com/products/analyzerpro/

AnalyzerPro​ is a productivity software application for both low and high resolution LC-MS and GC-MS data with support for multiple vendors’ data. This comprehensive post-processing utility provides optimized workflows for sample-to-sample comparison, target component analysis, quantitation and library searching for data generated from any LC-MS and GC-MS platform

Proprietary commercial software licence

**Comment by allysonlister** [comment]
Assigned SWO:1100136
