### ISSUE TITLE
Please add new term: Chromeleon

### ISSUE THREAD

**Issue by drmarkreuter** [allysonlister/swo#32]
Chromeleon

https://www.thermofisher.com/order/catalog/product/CHROMELEON7#/CHROMELEON7

Chromeleon software provides full integration of Thermo Scientific gas chromatography (GC-MS/MS), liquid chromatography (LC-MS/MS), and ion chromatography (IC-MS) instruments.

Proprietary commercial software licence

**Comment by allysonlister** [comment]
Assigned SWO:1100135
