### ISSUE TITLE
Wrong PURL in SWO

### ISSUE THREAD

**Issue by matentzn** [allysonlister/swo#48]
Hey! In our great [OBO wide effort to fix our PURLs](https://github.com/orgs/OBOFoundry/projects/5), I noticed the following wrong ones being used in SWO:

http://purl.obofoundry.org/obo/IAO_0000136

should be: 
http://purl.obolibrary.org/obo/IAO_0000136

**Comment by allysonlister** [comment]
Thanks so much @matentzn !

I'll get onto an update for that.
