### ISSUE TITLE
import issue with swo-external.owl

### ISSUE THREAD

**Issue by UTH-Tuan** [allysonlister/swo#51]
Hi,
I have swo as an import. I am using OBO Robot to merge the imports into one ontology file (import closure). However, I am getting an error relating to unable to import http://www.ebi.ac.uk/swo/swo-external.owl. ROBOT gives this as hint for the issue:

`
Cause: https://www.ebi.ac.uk/ols/ontologies/swo/terms?iri=http://www.ebi.ac.uk/swo/swo-external.owl
`

**Comment by allysonlister** [comment]
Please take a look at the files in the master release directory: https://github.com/allysonlister/swo/tree/master/release - the README there explains the various release files, and you can choose the one appropriate to you.

The swo-external.owl file is one of the files we use to build the release (as described here: https://github.com/allysonlister/swo/tree/master/dev/ontology), and is not of use as a standalone ontology.

I hope this helps!
